name: "Build project"
description: "Test if the project builds, if not then fail the build"

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Restore Packages
        run: nuget restore SillySCP.sln
      - name: Build solution
        run: msbuild SillySCP.sln -t:rebuild -property:Configuration=Debug